# fly.toml app configuration file generated for phonebook-backend-young-haze-3418 on 2024-11-13T16:31:15+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-backend-young-haze-3418'
primary_region = 'sin'

[build]

[env]
  PORT = "3000" # add this line

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
